version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: annum12/udagram-deployment
  backend_user:
    build:
      context: ../../udagram-api-users
    image: annum12/udagram-api-users
  backend_feed:
    build:
      context: ../../udagram-api-feed  
    image: annum12/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend  
    image: annum12/udagram-frontend
